apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          env:
            - name: GET_HOSTS_FROM
              value: "dns"
          image: gcr.io/pgtm-jlong/app-and-db:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          ports:
            - containerPort: 8080


#          envFrom:
#            - configMapRef:
#                name: mysql-config
#          volumeMounts:
#            - mountPath: /var/lib/
#              subPath: mysql
#              name: mysql

