---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: app
data:
  SPRING_R2DBC_PASSWORD: bp
  SPRING_R2DBC_USERNAME: bp
  SPRING_PROFILES_ACTIVE: cloud

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          envFrom:
            - configMapRef:
                name: app-config
#          env:
#            - name: GET_HOSTS_FROM
#              value: "dns"
          image: gcr.io/pgtm-jlong/app-and-db:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          ports:
            - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: app
  type: LoadBalancer
